keybinding:
  universal:
    quit: "w"
    scrollUpMain: "<C-t>"
    scrollDownMain: "<C-h>"
  files:
    commitChangesWithoutHook: "<C-C>"
  commits:
    moveUpCommit: "<pgup>"
    moveDownCommit: "<pgdown>"
