[package]
name = "zellij-runner"
description = "Session runner/switcher for Zellij"
authors = ["Alex Fedoseev <alex@fedoseev.mx>"]
version = "0.4.0"
readme = "README.md"
documentation = "https://docs.rs/zellij-runner"
repository = "https://github.com/alex35mil/dotfiles"
keywords = ["zellij"]
license = "MIT"
edition = "2021"

[dependencies]
tui = "0.19.0"
crossterm = "0.25"
console = "0.15.5"
dirs = "4.0.0"
ignore = "0.4.20"
unicode-width = "0.1"
once_cell = "1.17.0"
fastrand = "1.9.0"
